### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Travis failed

**Comment by greg0ire** [comment]
@OskarStark can you please help me on this? I think it's related to the new strictness

**Comment by OskarStark** [comment]
sure thing, but only the `lint`-job is failing, which should be fixed by FlintCI 🤔

**Comment by greg0ire** [comment]
Blocked by #307

**Comment by OskarStark** [comment]
Merged #307

**Pull request merged**
