### PR TITLE
Replace deprecated render tag with function

### PR DESCRIPTION
**Pull request by jeantristan**
I'm targeting branch 3.x cause it's a bugfix.

Fixes : No open issues.

## Changelog

```markdown
### Fixed : Change call of render function to make it compatible with Symfony greater than 3.0
Cf. https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md and Twig Bridge section
```

## Subject

Change from a render tag to a render function

### CODE REVIEW

**Comment by greg0ire** [comment]
Another one? Thanks. Should be the last, I checked.

**Comment by jeantristan** [comment]
Should be the last one.
Do you think it's possible there is a link between this fix and the CSRF error I get ?

**Comment by greg0ire** [comment]
>  Do you think it's possible there is a link between this fix and the CSRF error I get ?

No I don't. I think you had both problem and you have just moved on to the next error message. If you want some help, you can ask your question on SO and link to it here, I'll take a look.

**Comment by jeantristan** [comment]
Ok thanks. I just posted on SO.
I don't know where to look at to solve this issue for the moment.
http://stackoverflow.com/questions/38736578/symfony2-sonataadmin-got-an-csrf-error-when-trying-to-update-a-record

**Comment by jeantristan** [comment]
@greg0ire I've found the solution: http://stackoverflow.com/questions/38736578/symfony2-sonataadmin-got-an-csrf-error-when-trying-to-update-a-record/38762707#38762707

It was caused by my Vagrant setup. The sessions were not handled correctly.

**Pull request merged**
