### PR TITLE
Deprecate ModelManager::getMetadata and ModelManager::hasMetadata

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

In `sonata-project/admin-bundle` 4.0, `FieldDescription` will always contain mapping information when is created and cannot be changed, so there is no need to update again the mapping information.

`ModelManager::getMetadata` will be private in 4.0.

The commented code introduced in builders is the code inside the `if`s above that doesn't have to do with setting mapping to the `FieldDescriptionInterface`.

I am targeting this branch, because these changes are BC.

Closes #461.

## Changelog

```markdown
### Deprecated
- Deprecated `ModelManager::getMetadata()` method.
- Deprecated `ModelManager::hasMetadata()` method.
```

### CODE REVIEW

**Comment by franmomu** [comment]
friendly ping @sonata-project/contributors for reviews so I can finish preparing `4.x` branch for release

**Comment by VincentLanglet** [comment]
> friendly ping @sonata-project/contributors for reviews so I can finish preparing `4.x` branch for release

You want to release 4.x branch of this repository before the release of Sonata admin 4.x ?

**Review by VincentLanglet — APPROVED** [review]

**Comment by franmomu** [comment]
> You want to release 4.x branch of this repository before the release of Sonata admin 4.x ?

Nope, it doesn't make sense, by finish preparing I meant to finish some pending tasks like closing the api

**Review by OskarStark — APPROVED** [review]
Looks good to me

**Comment by VincentLanglet** [comment]
Thanks @franmomu

**Pull request merged**
