### PR TITLE
Moves crud association templates to admin-bundle

### PR DESCRIPTION
**Pull request by ju1ius**
This PR is related to [SonataAdminBundle#3971](https://github.com/sonata-project/SonataAdminBundle/pull/3971)
I am targetting this branch, because there are BC breaks
## Changelog

``` markdown
### Added
- `FieldDescription` implements `FieldDescriptionInterface::describesSingleValuedAssociation` and `FieldDescriptionInterface::describesCollectionValuedAssociation` methods

### Changed
- `FormContractor` now extends `Sonata\AdminBundle\Admin\AbstractFormContractor`

### Removed
- removed ALL crud association templates and form widget blocks. They now belong to the admin bundle
```

### CODE REVIEW

**Comment by core23** [comment]
Can we close this, after merging this https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/772?

**Comment by core23** [comment]
Have you checked this, if everything in this PR has bee merged? @OskarStark

**Comment by core23** [comment]
Picked the wrong repo => reopening this

**Comment by OskarStark** [comment]
> Have you checked this, if everything in this PR has been merged? @OskarStark

no, BUT this is very old, it diverged a lot, no feedback from @ju1ius .... these are enough reasons to close the PR for me

**Pull request closed without merging**
