### PR TITLE
[sormes-dev] implement interface method

### LINKED ISSUE #506: Pager contains 1 abstract method and must therefore be declared
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle                  dev-master 08dbbf1 dev-master 08dbbf1 The missing Symfony Admin Generator
sonata-project/block-bundle                  4.5.0              4.5.0              Symfony SonataBlockBundle
sonata-project/cache                         2.1.0              2.1.0              Cache library
sonata-project/doctrine-extensions           1.11.0             1.11.0             Doctrine2 behavioral extensions
sonata-project/doctrine-mongodb-admin-bundle dev-master 12d8ab2 dev-master 12d8ab2 Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/exporter                      2.5.0              2.5.0              Lightweight Exporter library
sonata-project/form-extensions               1.8.1              1.8.1              Symfony form extensions
sonata-project/twig-extensions               1.5.0              1.5.0              Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v5.2.1  v5.2.1  Symfony Asset Component
symfony/browser-kit                v5.2.1  v5.2.1  Symfony BrowserKit Component
symfony/cache                      v5.2.1  v5.2.1  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                     v5.2.1  v5.2.1  Symfony Config Component
symfony/console                    v5.2.1  v5.2.1  Symfony Console Component
symfony/css-selector               v5.2.1  v5.2.1  Symfony CssSelector Component
symfony/debug-bundle               v5.2.1  v5.2.1  Symfony DebugBundle
symfony/dependency-injection       v5.2.1  v5.2.1  Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.2.1  v5.2.1  Symfony Doctrine Bridge
symfony/dom-crawler                v5.2.1  v5.2.1  Symfony DomCrawler Component
symfony/dotenv                     v5.2.1  v5.2.1  Registers environment variables from a .env file
symfony/error-handler              v5.2.1  v5.2.1  Symfony ErrorHandler Component
symfony/event-dispatcher           v5.2.1  v5.2.1  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v2.2.0  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.2.1  v5.2.1  Symfony ExpressionLanguage Component
symfony/filesystem                 v5.2.1  v5.2.1  Symfony Filesystem Component
symfony/finder                     v5.2.1  v5.2.1  Symfony Finder Component
symfony/flex                       v1.11.0 v1.11.0 Composer plugin for Symfony
symfony/form                       v5.2.1  v5.2.1  Symfony Form Component
symfony/framework-bundle           v5.2.1  v5.2.1  Symfony FrameworkBundle
symfony/http-client                v5.2.1  v5.2.1  Symfony HttpClient component
symfony/http-client-contracts      v2.3.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.2.1  v5.2.1  Symfony HttpFoundation Component
symfony/http-kernel                v5.2.1  v5.2.1  Symfony HttpKernel Component
symfony/intl                       v5.2.1  v5.2.1  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                     v5.2.1  v5.2.1  Symfony Mailer Component
symfony/maker-bundle               1.27.0  1.27.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v5.2.1  v5.2.1  A library to manipulate MIME messages
symfony/monolog-bridge             v5.2.1  v5.2.1  Symfony Monolog Bridge
symfony/monolog-bundle             v3.6.0  v3.6.0  Symfony MonologBundle
symfony/options-resolver           v5.2.1  v5.2.1  Symfony OptionsResolver Component
symfony/phpunit-bridge             v5.2.1  v5.2.1  Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme     v1.22.0 v1.22.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.0 v1.22.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.22.0 v1.22.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.22.0 v1.22.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.0 v1.22.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.22.0 v1.22.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.22.0 v1.22.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.22.0 v1.22.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v5.2.1  v5.2.1  Symfony Process Component
symfony/property-access            v5.2.1  v5.2.1  Symfony PropertyAccess Component
symfony/property-info              v5.2.1  v5.2.1  Symfony Property Info Component
symfony/routing                    v5.2.1  v5.2.1  Symfony Routing Component
symfony/security-acl               v3.1.1  v3.1.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.2.1  v5.2.1  Symfony SecurityBundle
symfony/security-core              v5.2.1  v5.2.1  Symfony Security Component - Core Library
symfony/security-csrf              v5.2.1  v5.2.1  Symfony Security Component - CSRF Library
symfony/security-guard             v5.2.1  v5.2.1  Symfony Security Component - Guard
symfony/security-http              v5.2.1  v5.2.1  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.2.1  v5.2.1  Symfony Serializer Component
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.2.1  v5.2.1  Symfony Stopwatch Component
symfony/string                     v5.2.1  v5.2.1  Symfony String component
symfony/translation                v5.2.1  v5.2.1  Symfony Translation Component
symfony/translation-contracts      v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v5.2.1  v5.2.1  Symfony Twig Bridge
symfony/twig-bundle                v5.2.1  v5.2.1  Symfony TwigBundle
symfony/validator                  v5.2.1  v5.2.1  Symfony Validator Component
symfony/var-dumper                 v5.2.1  v5.2.1  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v5.2.1  v5.2.1  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v5.2.1  v5.2.1  Symfony WebLink Component
symfony/web-profiler-bundle        v5.2.1  v5.2.1  Symfony WebProfilerBundle
symfony/yaml                       v5.2.1  v5.2.1  Symfony Yaml Component
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.3.25 (cli) (built: Nov 30 2020 14:17:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

```
Error: Class Sonata\DoctrineMongoDBAdminBundle\Datagrid\Pager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Sonata\AdminBundle\Datagrid\PagerInterface::countResults)
```

### PR DESCRIPTION
**Pull request by sormes**
## Subject

I am targeting this branch, because BC break

Closes #506 .

## Changelog

```markdown
### Added
- Added  `Pager:: countResults()`
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @sormes.

This PR is not providing any BC-break so it can be done on 3.x (to avoid the deprecation) and then we'll merge into master.
Plus the goal was to remove the `NbResult` word. 

I recommend you to do the same things than this PR:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1257

And then, to avoid the same error with `getCurrentPageResult`, this PR should also be done to this repository
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1262

**Comment by sormes** [comment]
> Hi @sormes.
> 
> This PR is not providing any BC-break so it can be done on 3.x (to avoid the deprecation) and then we'll merge into master.
> Plus the goal was to remove the `NbResult` word.


Should I create a new branch and a new PR?

**Comment by VincentLanglet** [comment]
> Should I create a new branch and a new PR?

Yes, you should create a branch from the 3.x (instead of the master).

**Comment by sormes** [comment]
@VincentLanglet 

I think this issue is resolved in 3.x branch because the method already exists

https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Datagrid/Pager.php#L35


I'm right? should we close this PR and #506 ?

**Comment by VincentLanglet** [comment]
> @VincentLanglet
> 
> I think this issue is resolved in 3.x branch because the method already exists
> 
> https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Datagrid/Pager.php#L35
> 
> I'm right? should we close this PR and #506 ?

Ok, so what we need is to merge 3.x into master and fix the conflicts.

You can tried it, or me or @franmomu we'll do it when we'll find time ;)

**Comment by sormes** [comment]
@VincentLanglet 

I created https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/508

**Pull request closed without merging**
