### PR TITLE
Update all templates references to Twig namespaced syntax

### PR DESCRIPTION
**Pull request by covex-nn**
I am targeting this branch, because it is patch.

## Changelog

```markdown
### Changed
- All templates references are updated to twig namespaced syntax
```

## Subject

This PR is a part of a big plan of decoupling sonata-project bundles from Templating Component. See https://github.com/sonata-project/dev-kit/issues/380 for details

### CODE REVIEW

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already pushed. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by greg0ire** [comment]
Should we label this as pedantic?

**Comment by jordisala1991** [comment]
IMO docs and patch, please fix flintCI @covex-nn

**Comment by OskarStark** [comment]
> Should we label this as pedantic?
patch is fine 👍

**Comment by covex-nn** [comment]
@greg0ire @jordisala1991 Unit tests were failing for first comment https://travis-ci.org/sonata-project/SonataDoctrineMongoDBAdminBundle/builds/329790360, but i do not know why. Are my changes related?

**Comment by covex-nn** [comment]
Tests were failing because `1.3.0` of `[doctrine/inflector](https://packagist.org/packages/doctrine/inflector)` were released. With `1.2.0 ` everything is ok.

**Comment by greg0ire** [comment]
Please don't require 1.2 , and fix the code instead. Calling `classify` with `null` makes no sense, we shouldn't do it, although it might be considered a BC-break

**Comment by covex-nn** [comment]
@greg0ire Ok, i'll fix code and tests. But i was so close! =))

**Comment by greg0ire** [comment]
If you need help I am here: https://symfony.com/slack-invite

**Comment by covex-nn** [comment]
@greg0ire google translate is not so fast on read/write as english native speaker =) So, i fixed bug and created PR https://github.com/sonata-project/SonataAdminBundle/pull/4896

**Comment by covex-nn** [comment]
@greg0ire bug fixed and travis is green

**Pull request merged**
