### PR TITLE
fix the association on Reference One and List Ajax

### PR DESCRIPTION
**Pull request by joshlopes**
Q   |   A
------|-------
Bug fix? |	yes
New feature? |	no
BC breaks? |	no
Deprecations? |	no
Tests pass? | yes
Fixed tickets | https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/issues/139
License | no
Doc PR | no

### CODE REVIEW

**Comment by joshlopes** [comment]
Bump -- Compared with the ORM versions of the model_type_list and make them as most identical as it is possible. It fixed a lot of bugs in views and enabled the new options including help etc.

**Comment by joshlopes** [comment]
@dunglas @rande please review this one. Thank you.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by kwuerl** [comment]
I'm in need of this PR and I was about to send in almost exactly the same changes as PR when I found this one.
On which branch should this PR be submitted? master 2.x or 3.x ?
I need this in 3.x but I guess it also fixes the filter in the popup for 2.x...

**Pull request closed without merging**
