### PR TITLE
Mark classes as final

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

Similar to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1127

I am targeting this branch, because these changes are BC.

## Changelog

```markdown
### Changed
- Mark some classes as final.
```

### CODE REVIEW

**Review by VincentLanglet — COMMENTED** [review]
I didn't take attention to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1127/files#diff-5932af620464f5fdaec84991e9c2f0faR43

But in my personal project I override the ModelManager,
- I override the `getDataSourceIterator` to use my own SourceIterator

And I think that someone could just want to override some config methods like
```
getDefaultSortValues
getDefaultPerPageOptions
...
```

How to do this if the ModelManager is final ?
cc @core23 (and @sonata-project/contributors), we may have to revert this final annotation.

**Comment by core23** [comment]
We decided that we make everything final by default unless someone give a good reason why they can't use service decoration. 

We should decide it on an individual basis.

**Comment by VincentLanglet** [comment]
> We decided that we make everything final by default unless someone give a good reason why they can't use service decoration.
> 
> We should decide it on an individual basis.

Yes, that's why I gave reasons. And I was looking for confirmation that it was good reasons ^^

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Let's go with this. I'll make a new release after this merge.

**Review by core23 — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks @franmomu

**Pull request merged**
