### PR TITLE
Add psalm

### PR DESCRIPTION
**Pull request by franmomu**
- [x] Add psalm without https://github.com/psalm/psalm-github-actions it we agree with it.

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

**Comment by franmomu** [comment]
I guess we have the same problem we had with phpstan, but I think there is no way to ignore platform requirements for that github action, I'll open an issue later.

**Review by core23 — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
This will require https://github.com/sonata-project/dev-kit/pull/1177 @OskarStark

**Comment by OskarStark** [comment]
Thank you!

**Comment by OskarStark** [comment]
> This will require sonata-project/dev-kit#1177 @OskarStark

Merged and deployed 👍

**Pull request merged**
