### PR TITLE
RC 1

### PR DESCRIPTION
**Pull request by franmomu**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
This https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/617/commits/bd81f6b7673857d39734611391d734f11edc3399 wasn't merged, isn't it ?

**Comment by franmomu** [comment]
I'll create from `4.x` branch.

**Comment by VincentLanglet** [comment]
> I'll create it from `4.x` branch.

You have to run `bin/console release` with the master branch, since there is currently no release on the 4.x.

**Comment by franmomu** [comment]
👍 thanks

**Pull request closed without merging**
