### PR TITLE
Adding sort by embedded value

### PR DESCRIPTION
**Pull request by atrigub**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Can you please explain a little bit this PR?

**Comment by atrigub** [comment]
@Soullivaneuh In this time I can not sort by embedded document's field. For example I have document

/** @Document */
class Page
{
    // ...

    /** @EmbedOne(targetDocument="Statistic") */
    private $statistic;

    // ...
}

/** @EmbeddedDocument */
class Statistic
{
    // ...
    private $someField
}

And in PageAdmin

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('id')
            ->add('statistic.someField')
           //... 
            ;
    }

At this time I can not order by $someField.

**Comment by joshlopes** [comment]
@Soullivaneuh in Mongo you have this embed Documents logic where its something like ORM relations One to One or One to Many. In order to sort for it, you need to access the property by parent(dot)children. 

This PR is checking for parent mappings (embed documents) and convert it to a valid property level (with dot annotation) so mongo can filter by it. 

I did not checked, tried / review it i do remember doing something similar: https://github.com/joshlopes/SonataDoctrineMongoDBAdminBundle/blob/b41861c2dfb74a0100245d4fcff1c26f683bc9e7/Filter/Filter.php#L35 actually i think you can simplify the logic using the same @atrigub if not my PR already solves this issue! 

@atrigub can you try merging with my PR https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/137 and test that?

**Comment by atrigub** [comment]
@joshlopes I've used your solution in my project. And this solution works fine for filter results, but it is not working for sorting. Parameter _sort_by should be instanceof FieldDescriptionInterface.

**Comment by atrigub** [comment]
@Soullivaneuh @joshlopes Hi guys! Maybe need update getSortFieldMapping() in Sonata\DoctrineMongoDBAdminBundle\Admin\FieldDescription? Maybe, is it better than current solution?

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
